/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  ApiResponseBoolean,
  ApiResponseLoginResponse,
  ApiResponseString,
  ApiResponseTwoFactorSetupResponse,
  ApiResponseUserResponse,
  Enable2FAWithSecretRequest,
  LoginRequest,
  RefreshTokenRequest,
  RegisterRequest,
  ResendVerificationEmailParams,
  VerifyEmailParams,
} from '../models/auth';

import { customInstance } from '../apiClient';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const resendVerificationEmail = (
  params: ResendVerificationEmailParams,
  options?: SecondParameter<typeof customInstance<ApiResponseString>>
) => {
  return customInstance<ApiResponseString>(
    { url: `/auth/resend-verification`, method: 'POST', params },
    options
  );
};

export const register = (
  registerRequest: RegisterRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseUserResponse>>
) => {
  return customInstance<ApiResponseUserResponse>(
    {
      url: `/auth/register`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: registerRequest,
    },
    options
  );
};

export const refreshToken = (
  refreshTokenRequest: RefreshTokenRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseLoginResponse>>
) => {
  return customInstance<ApiResponseLoginResponse>(
    {
      url: `/auth/refresh`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: refreshTokenRequest,
    },
    options
  );
};

export const login = (
  loginRequest: LoginRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseLoginResponse>>
) => {
  return customInstance<ApiResponseLoginResponse>(
    {
      url: `/auth/login`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: loginRequest,
    },
    options
  );
};

export const enable2FA = (
  enable2FAWithSecretRequest: Enable2FAWithSecretRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseString>>
) => {
  return customInstance<ApiResponseString>(
    {
      url: `/auth/2fa/enable`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: enable2FAWithSecretRequest,
    },
    options
  );
};

export const disable2FA = (
  options?: SecondParameter<typeof customInstance<ApiResponseString>>
) => {
  return customInstance<ApiResponseString>(
    { url: `/auth/2fa/disable`, method: 'POST' },
    options
  );
};

export const getUserById = (
  id: string,
  options?: SecondParameter<typeof customInstance<ApiResponseUserResponse>>
) => {
  return customInstance<ApiResponseUserResponse>(
    { url: `/users/${id}`, method: 'GET' },
    options
  );
};

export const getUserEmail = (
  id: string,
  options?: SecondParameter<typeof customInstance<string>>
) => {
  return customInstance<string>(
    { url: `/users/${id}/email`, method: 'GET' },
    options
  );
};

export const getCurrentUser = (
  options?: SecondParameter<typeof customInstance<ApiResponseUserResponse>>
) => {
  return customInstance<ApiResponseUserResponse>(
    { url: `/users/me`, method: 'GET' },
    options
  );
};

export const verifyEmail = (
  params: VerifyEmailParams,
  options?: SecondParameter<typeof customInstance<ApiResponseString>>
) => {
  return customInstance<ApiResponseString>(
    { url: `/auth/verify-email`, method: 'GET', params },
    options
  );
};

export const health = (
  options?: SecondParameter<typeof customInstance<ApiResponseString>>
) => {
  return customInstance<ApiResponseString>(
    { url: `/auth/health`, method: 'GET' },
    options
  );
};

export const get2FAStatus = (
  options?: SecondParameter<typeof customInstance<ApiResponseBoolean>>
) => {
  return customInstance<ApiResponseBoolean>(
    { url: `/auth/2fa/status`, method: 'GET' },
    options
  );
};

export const generateSetup = (
  options?: SecondParameter<
    typeof customInstance<ApiResponseTwoFactorSetupResponse>
  >
) => {
  return customInstance<ApiResponseTwoFactorSetupResponse>(
    { url: `/auth/2fa/setup`, method: 'GET' },
    options
  );
};

export type ResendVerificationEmailResult = NonNullable<
  Awaited<ReturnType<typeof resendVerificationEmail>>
>;
export type RegisterResult = NonNullable<Awaited<ReturnType<typeof register>>>;
export type RefreshTokenResult = NonNullable<
  Awaited<ReturnType<typeof refreshToken>>
>;
export type LoginResult = NonNullable<Awaited<ReturnType<typeof login>>>;
export type Enable2FAResult = NonNullable<
  Awaited<ReturnType<typeof enable2FA>>
>;
export type Disable2FAResult = NonNullable<
  Awaited<ReturnType<typeof disable2FA>>
>;
export type GetUserByIdResult = NonNullable<
  Awaited<ReturnType<typeof getUserById>>
>;
export type GetUserEmailResult = NonNullable<
  Awaited<ReturnType<typeof getUserEmail>>
>;
export type GetCurrentUserResult = NonNullable<
  Awaited<ReturnType<typeof getCurrentUser>>
>;
export type VerifyEmailResult = NonNullable<
  Awaited<ReturnType<typeof verifyEmail>>
>;
export type HealthResult = NonNullable<Awaited<ReturnType<typeof health>>>;
export type Get2FAStatusResult = NonNullable<
  Awaited<ReturnType<typeof get2FAStatus>>
>;
export type GenerateSetupResult = NonNullable<
  Awaited<ReturnType<typeof generateSetup>>
>;
