/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  AddCartItemRequest,
  ApiResponseCartItemResponse,
  ApiResponseCartResponse,
  ApiResponseDnsRecordResponse,
  ApiResponseDomainResponse,
  ApiResponseListDnsRecordResponse,
  ApiResponseListDomainSearchResult,
  ApiResponseNsDelegationResponse,
  ApiResponseOrderResponse,
  ApiResponsePageDomainResponse,
  ApiResponsePageOrderResponse,
  ApiResponsePageZone,
  ApiResponseString,
  ApiResponseVoid,
  ApiResponseZone,
  CreateARecordRequest,
  CreateAaaaRecordRequest,
  CreateCaaRecordRequest,
  CreateCnameRecordRequest,
  CreateDomainRequest,
  CreateMxRecordRequest,
  CreateOrderRequest,
  CreateSrvRecordRequest,
  CreateTxtRecordRequest,
  CreateZoneRequest,
  GetAllDomainsParams,
  GetAllZonesParams,
  GetOrdersParams,
  NsDelegationRequest,
  SearchDomainsParams,
  UpdateDnsRecordRequest,
  UpdateDomainRequest,
  UpdateOrderStatusParams,
  UpdateZoneRequest,
} from '../models/domain-order';

import { customInstance } from '../apiClientDomains';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getZoneById = (
  id: string,
  options?: SecondParameter<typeof customInstance<ApiResponseZone>>
) => {
  return customInstance<ApiResponseZone>(
    { url: `/zones/${id}`, method: 'GET' },
    options
  );
};

export const updateZone = (
  id: string,
  updateZoneRequest: UpdateZoneRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseZone>>
) => {
  return customInstance<ApiResponseZone>(
    {
      url: `/zones/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateZoneRequest,
    },
    options
  );
};

export const deleteZone = (
  id: string,
  options?: SecondParameter<typeof customInstance<ApiResponseVoid>>
) => {
  return customInstance<ApiResponseVoid>(
    { url: `/zones/${id}`, method: 'DELETE' },
    options
  );
};

export const updateOrderStatus = (
  id: string,
  params: UpdateOrderStatusParams,
  options?: SecondParameter<typeof customInstance<ApiResponseOrderResponse>>
) => {
  return customInstance<ApiResponseOrderResponse>(
    { url: `/orders/${id}/status`, method: 'PUT', params },
    options
  );
};

export const getDomainById = (
  id: string,
  options?: SecondParameter<typeof customInstance<ApiResponseDomainResponse>>
) => {
  return customInstance<ApiResponseDomainResponse>(
    { url: `/domains/${id}`, method: 'GET' },
    options
  );
};

export const updateDomain = (
  id: string,
  updateDomainRequest: UpdateDomainRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseDomainResponse>>
) => {
  return customInstance<ApiResponseDomainResponse>(
    {
      url: `/domains/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateDomainRequest,
    },
    options
  );
};

export const deleteDomain = (
  id: string,
  options?: SecondParameter<typeof customInstance<ApiResponseVoid>>
) => {
  return customInstance<ApiResponseVoid>(
    { url: `/domains/${id}`, method: 'DELETE' },
    options
  );
};

export const getRecordById = (
  recordId: string,
  options?: SecondParameter<typeof customInstance<ApiResponseDnsRecordResponse>>
) => {
  return customInstance<ApiResponseDnsRecordResponse>(
    { url: `/dns/records/${recordId}`, method: 'GET' },
    options
  );
};

export const updateRecord = (
  recordId: string,
  updateDnsRecordRequest: UpdateDnsRecordRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseDnsRecordResponse>>
) => {
  return customInstance<ApiResponseDnsRecordResponse>(
    {
      url: `/dns/records/${recordId}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateDnsRecordRequest,
    },
    options
  );
};

export const deleteRecord = (
  recordId: string,
  options?: SecondParameter<typeof customInstance<ApiResponseVoid>>
) => {
  return customInstance<ApiResponseVoid>(
    { url: `/dns/records/${recordId}`, method: 'DELETE' },
    options
  );
};

export const getDelegation = (
  domainId: string,
  options?: SecondParameter<
    typeof customInstance<ApiResponseNsDelegationResponse>
  >
) => {
  return customInstance<ApiResponseNsDelegationResponse>(
    { url: `/dns/delegation/domain/${domainId}`, method: 'GET' },
    options
  );
};

export const setDelegation = (
  domainId: string,
  nsDelegationRequest: NsDelegationRequest,
  options?: SecondParameter<
    typeof customInstance<ApiResponseNsDelegationResponse>
  >
) => {
  return customInstance<ApiResponseNsDelegationResponse>(
    {
      url: `/dns/delegation/domain/${domainId}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: nsDelegationRequest,
    },
    options
  );
};

export const removeDelegation = (
  domainId: string,
  options?: SecondParameter<typeof customInstance<ApiResponseVoid>>
) => {
  return customInstance<ApiResponseVoid>(
    { url: `/dns/delegation/domain/${domainId}`, method: 'DELETE' },
    options
  );
};

export const getAllZones = (
  params: GetAllZonesParams,
  options?: SecondParameter<typeof customInstance<ApiResponsePageZone>>
) => {
  return customInstance<ApiResponsePageZone>(
    { url: `/zones`, method: 'GET', params },
    options
  );
};

export const createZone = (
  createZoneRequest: CreateZoneRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseZone>>
) => {
  return customInstance<ApiResponseZone>(
    {
      url: `/zones`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createZoneRequest,
    },
    options
  );
};

export const getOrders = (
  params: GetOrdersParams,
  options?: SecondParameter<typeof customInstance<ApiResponsePageOrderResponse>>
) => {
  return customInstance<ApiResponsePageOrderResponse>(
    { url: `/orders`, method: 'GET', params },
    options
  );
};

export const createOrder = (
  createOrderRequest: CreateOrderRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseOrderResponse>>
) => {
  return customInstance<ApiResponseOrderResponse>(
    {
      url: `/orders`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createOrderRequest,
    },
    options
  );
};

export const cancelOrder = (
  id: string,
  options?: SecondParameter<typeof customInstance<ApiResponseOrderResponse>>
) => {
  return customInstance<ApiResponseOrderResponse>(
    { url: `/orders/${id}/cancel`, method: 'POST' },
    options
  );
};

export const getAllDomains = (
  params: GetAllDomainsParams,
  options?: SecondParameter<
    typeof customInstance<ApiResponsePageDomainResponse>
  >
) => {
  return customInstance<ApiResponsePageDomainResponse>(
    { url: `/domains`, method: 'GET', params },
    options
  );
};

export const createDomain = (
  createDomainRequest: CreateDomainRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseDomainResponse>>
) => {
  return customInstance<ApiResponseDomainResponse>(
    {
      url: `/domains`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createDomainRequest,
    },
    options
  );
};

export const activateDomain = (
  id: string,
  options?: SecondParameter<typeof customInstance<ApiResponseDomainResponse>>
) => {
  return customInstance<ApiResponseDomainResponse>(
    { url: `/domains/${id}/activate`, method: 'POST' },
    options
  );
};

export const createTxtRecord = (
  createTxtRecordRequest: CreateTxtRecordRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseDnsRecordResponse>>
) => {
  return customInstance<ApiResponseDnsRecordResponse>(
    {
      url: `/dns/records/txt`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createTxtRecordRequest,
    },
    options
  );
};

export const createSrvRecord = (
  createSrvRecordRequest: CreateSrvRecordRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseDnsRecordResponse>>
) => {
  return customInstance<ApiResponseDnsRecordResponse>(
    {
      url: `/dns/records/srv`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createSrvRecordRequest,
    },
    options
  );
};

export const createMxRecord = (
  createMxRecordRequest: CreateMxRecordRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseDnsRecordResponse>>
) => {
  return customInstance<ApiResponseDnsRecordResponse>(
    {
      url: `/dns/records/mx`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createMxRecordRequest,
    },
    options
  );
};

export const createCnameRecord = (
  createCnameRecordRequest: CreateCnameRecordRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseDnsRecordResponse>>
) => {
  return customInstance<ApiResponseDnsRecordResponse>(
    {
      url: `/dns/records/cname`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createCnameRecordRequest,
    },
    options
  );
};

export const createCaaRecord = (
  createCaaRecordRequest: CreateCaaRecordRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseDnsRecordResponse>>
) => {
  return customInstance<ApiResponseDnsRecordResponse>(
    {
      url: `/dns/records/caa`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createCaaRecordRequest,
    },
    options
  );
};

export const createAaaaRecord = (
  createAaaaRecordRequest: CreateAaaaRecordRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseDnsRecordResponse>>
) => {
  return customInstance<ApiResponseDnsRecordResponse>(
    {
      url: `/dns/records/aaaa`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createAaaaRecordRequest,
    },
    options
  );
};

export const createARecord = (
  createARecordRequest: CreateARecordRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseDnsRecordResponse>>
) => {
  return customInstance<ApiResponseDnsRecordResponse>(
    {
      url: `/dns/records/a`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createARecordRequest,
    },
    options
  );
};

export const addItem = (
  addCartItemRequest: AddCartItemRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseCartItemResponse>>
) => {
  return customInstance<ApiResponseCartItemResponse>(
    {
      url: `/cart/items`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: addCartItemRequest,
    },
    options
  );
};

export const getZoneByName = (
  name: string,
  options?: SecondParameter<typeof customInstance<ApiResponseZone>>
) => {
  return customInstance<ApiResponseZone>(
    { url: `/zones/name/${name}`, method: 'GET' },
    options
  );
};

export const getOrderById = (
  id: string,
  options?: SecondParameter<typeof customInstance<ApiResponseOrderResponse>>
) => {
  return customInstance<ApiResponseOrderResponse>(
    { url: `/orders/${id}`, method: 'GET' },
    options
  );
};

export const searchDomains = (
  params: SearchDomainsParams,
  options?: SecondParameter<
    typeof customInstance<ApiResponseListDomainSearchResult>
  >
) => {
  return customInstance<ApiResponseListDomainSearchResult>(
    { url: `/domains/search`, method: 'GET', params },
    options
  );
};

export const getDomainByFqdn = (
  fqdn: string,
  options?: SecondParameter<typeof customInstance<ApiResponseDomainResponse>>
) => {
  return customInstance<ApiResponseDomainResponse>(
    { url: `/domains/fqdn/${fqdn}`, method: 'GET' },
    options
  );
};

export const health = (
  options?: SecondParameter<typeof customInstance<ApiResponseString>>
) => {
  return customInstance<ApiResponseString>(
    { url: `/dns/records/health`, method: 'GET' },
    options
  );
};

export const getRecordsByDomain = (
  domainId: string,
  options?: SecondParameter<
    typeof customInstance<ApiResponseListDnsRecordResponse>
  >
) => {
  return customInstance<ApiResponseListDnsRecordResponse>(
    { url: `/dns/records/domain/${domainId}`, method: 'GET' },
    options
  );
};

export const health1 = (
  options?: SecondParameter<typeof customInstance<ApiResponseString>>
) => {
  return customInstance<ApiResponseString>(
    { url: `/dns/delegation/health`, method: 'GET' },
    options
  );
};

export const getCart = (
  options?: SecondParameter<typeof customInstance<ApiResponseCartResponse>>
) => {
  return customInstance<ApiResponseCartResponse>(
    { url: `/cart`, method: 'GET' },
    options
  );
};

export const clearCart = (
  options?: SecondParameter<typeof customInstance<ApiResponseVoid>>
) => {
  return customInstance<ApiResponseVoid>(
    { url: `/cart`, method: 'DELETE' },
    options
  );
};

export const removeItem = (
  itemId: string,
  options?: SecondParameter<typeof customInstance<ApiResponseVoid>>
) => {
  return customInstance<ApiResponseVoid>(
    { url: `/cart/items/${itemId}`, method: 'DELETE' },
    options
  );
};

export type GetZoneByIdResult = NonNullable<
  Awaited<ReturnType<typeof getZoneById>>
>;
export type UpdateZoneResult = NonNullable<
  Awaited<ReturnType<typeof updateZone>>
>;
export type DeleteZoneResult = NonNullable<
  Awaited<ReturnType<typeof deleteZone>>
>;
export type UpdateOrderStatusResult = NonNullable<
  Awaited<ReturnType<typeof updateOrderStatus>>
>;
export type GetDomainByIdResult = NonNullable<
  Awaited<ReturnType<typeof getDomainById>>
>;
export type UpdateDomainResult = NonNullable<
  Awaited<ReturnType<typeof updateDomain>>
>;
export type DeleteDomainResult = NonNullable<
  Awaited<ReturnType<typeof deleteDomain>>
>;
export type GetRecordByIdResult = NonNullable<
  Awaited<ReturnType<typeof getRecordById>>
>;
export type UpdateRecordResult = NonNullable<
  Awaited<ReturnType<typeof updateRecord>>
>;
export type DeleteRecordResult = NonNullable<
  Awaited<ReturnType<typeof deleteRecord>>
>;
export type GetDelegationResult = NonNullable<
  Awaited<ReturnType<typeof getDelegation>>
>;
export type SetDelegationResult = NonNullable<
  Awaited<ReturnType<typeof setDelegation>>
>;
export type RemoveDelegationResult = NonNullable<
  Awaited<ReturnType<typeof removeDelegation>>
>;
export type GetAllZonesResult = NonNullable<
  Awaited<ReturnType<typeof getAllZones>>
>;
export type CreateZoneResult = NonNullable<
  Awaited<ReturnType<typeof createZone>>
>;
export type GetOrdersResult = NonNullable<
  Awaited<ReturnType<typeof getOrders>>
>;
export type CreateOrderResult = NonNullable<
  Awaited<ReturnType<typeof createOrder>>
>;
export type CancelOrderResult = NonNullable<
  Awaited<ReturnType<typeof cancelOrder>>
>;
export type GetAllDomainsResult = NonNullable<
  Awaited<ReturnType<typeof getAllDomains>>
>;
export type CreateDomainResult = NonNullable<
  Awaited<ReturnType<typeof createDomain>>
>;
export type ActivateDomainResult = NonNullable<
  Awaited<ReturnType<typeof activateDomain>>
>;
export type CreateTxtRecordResult = NonNullable<
  Awaited<ReturnType<typeof createTxtRecord>>
>;
export type CreateSrvRecordResult = NonNullable<
  Awaited<ReturnType<typeof createSrvRecord>>
>;
export type CreateMxRecordResult = NonNullable<
  Awaited<ReturnType<typeof createMxRecord>>
>;
export type CreateCnameRecordResult = NonNullable<
  Awaited<ReturnType<typeof createCnameRecord>>
>;
export type CreateCaaRecordResult = NonNullable<
  Awaited<ReturnType<typeof createCaaRecord>>
>;
export type CreateAaaaRecordResult = NonNullable<
  Awaited<ReturnType<typeof createAaaaRecord>>
>;
export type CreateARecordResult = NonNullable<
  Awaited<ReturnType<typeof createARecord>>
>;
export type AddItemResult = NonNullable<Awaited<ReturnType<typeof addItem>>>;
export type GetZoneByNameResult = NonNullable<
  Awaited<ReturnType<typeof getZoneByName>>
>;
export type GetOrderByIdResult = NonNullable<
  Awaited<ReturnType<typeof getOrderById>>
>;
export type SearchDomainsResult = NonNullable<
  Awaited<ReturnType<typeof searchDomains>>
>;
export type GetDomainByFqdnResult = NonNullable<
  Awaited<ReturnType<typeof getDomainByFqdn>>
>;
export type HealthResult = NonNullable<Awaited<ReturnType<typeof health>>>;
export type GetRecordsByDomainResult = NonNullable<
  Awaited<ReturnType<typeof getRecordsByDomain>>
>;
export type Health1Result = NonNullable<Awaited<ReturnType<typeof health1>>>;
export type GetCartResult = NonNullable<Awaited<ReturnType<typeof getCart>>>;
export type ClearCartResult = NonNullable<
  Awaited<ReturnType<typeof clearCart>>
>;
export type RemoveItemResult = NonNullable<
  Awaited<ReturnType<typeof removeItem>>
>;
