/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Exdns HTTP API
 * OpenAPI spec version: 0.1.0
 */
import type {
  DeleteZonesDomain200,
  PostZonesDomain201,
  PutZonesDomain200,
  Zone,
} from '../models/exdns';

import { customInstance } from '../apiClientExdns';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get zone
 */
export const getZonesDomain = (
  domain: string,
  options?: SecondParameter<typeof customInstance<Zone>>
) => {
  return customInstance<Zone>(
    { url: `/zones/${domain}`, method: 'GET' },
    options
  );
};

/**
 * @summary Create zone
 */
export const postZonesDomain = (
  domain: string,
  zone: Zone,
  options?: SecondParameter<typeof customInstance<PostZonesDomain201>>
) => {
  return customInstance<PostZonesDomain201>(
    {
      url: `/zones/${domain}`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: zone,
    },
    options
  );
};

/**
 * @summary Update zone
 */
export const putZonesDomain = (
  domain: string,
  zone: Zone,
  options?: SecondParameter<typeof customInstance<PutZonesDomain200>>
) => {
  return customInstance<PutZonesDomain200>(
    {
      url: `/zones/${domain}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: zone,
    },
    options
  );
};

/**
 * @summary Delete zone
 */
export const deleteZonesDomain = (
  domain: string,
  options?: SecondParameter<typeof customInstance<DeleteZonesDomain200>>
) => {
  return customInstance<DeleteZonesDomain200>(
    { url: `/zones/${domain}`, method: 'DELETE' },
    options
  );
};

export type GetZonesDomainResult = NonNullable<
  Awaited<ReturnType<typeof getZonesDomain>>
>;
export type PostZonesDomainResult = NonNullable<
  Awaited<ReturnType<typeof postZonesDomain>>
>;
export type PutZonesDomainResult = NonNullable<
  Awaited<ReturnType<typeof putZonesDomain>>
>;
export type DeleteZonesDomainResult = NonNullable<
  Awaited<ReturnType<typeof deleteZonesDomain>>
>;
