/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiErrorDetails } from './apiErrorDetails';

export interface ApiError {
  code?: string;
  message?: string;
  details?: ApiErrorDetails;
}
