/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TwoFactorSetupResponse } from './twoFactorSetupResponse';
import type { ApiError } from './apiError';

export interface ApiResponseTwoFactorSetupResponse {
  success?: boolean;
  data?: TwoFactorSetupResponse;
  message?: string;
  error?: ApiError;
}
