/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { LoginResponse } from './loginResponse';
import type { ApiError } from './apiError';

export interface ApiResponseLoginResponse {
  success?: boolean;
  data?: LoginResponse;
  message?: string;
  error?: ApiError;
}
