/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface Enable2FAWithSecretRequest {
  secret: string;
  /** @pattern ^\d{6}$ */
  code: string;
}
