/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface LoginResponse {
  userId?: string;
  accessToken?: string;
  refreshToken?: string;
  email?: string;
}
