/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface RegisterRequest {
  email: string;
  /**
   * @minLength 8
   * @maxLength 2147483647
   */
  password: string;
}
