/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UserResponse {
  id?: string;
  email?: string;
  createdAt?: string;
  updatedAt?: string;
}
