/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Exdns HTTP API
 * OpenAPI spec version: 0.1.0
 */

export * from './deleteZonesDomain200';
export * from './error';
export * from './postZonesDomain201';
export * from './putZonesDomain200';
export * from './record';
export * from './recordType';
export * from './zone';
