/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Exdns HTTP API
 * OpenAPI spec version: 0.1.0
 */

export type RecordType = (typeof RecordType)[keyof typeof RecordType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RecordType = {
  A: 'A',
  AAAA: 'AAAA',
  NS: 'NS',
  PTR: 'PTR',
  MX: 'MX',
  TXT: 'TXT',
  SOA: 'SOA',
  CNAME: 'CNAME',
} as const;
