/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Exdns HTTP API
 * OpenAPI spec version: 0.1.0
 */
import type { RecordType } from './recordType';

export interface Record {
  name: string;
  type: RecordType;
  ttl: number;
  data: unknown;
}
