/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Exdns HTTP API
 * OpenAPI spec version: 0.1.0
 */
import type { Record } from './record';

export interface Zone {
  name: string;
  version: number;
  records: Record[];
}
