/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type AddCartItemRequestAction =
  (typeof AddCartItemRequestAction)[keyof typeof AddCartItemRequestAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AddCartItemRequestAction = {
  register: 'register',
  renew: 'renew',
} as const;
