/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type AddCartItemRequestTerm =
  (typeof AddCartItemRequestTerm)[keyof typeof AddCartItemRequestTerm];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AddCartItemRequestTerm = {
  monthly: 'monthly',
  yearly: 'yearly',
} as const;
