/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AddCartItemRequestAction } from './addCartItemRequestAction';
import type { AddCartItemRequestTerm } from './addCartItemRequestTerm';

export interface AddCartItemRequest {
  action: AddCartItemRequestAction;
  term: AddCartItemRequestTerm;
  fqdn: string;
  price: number;
}
