/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageOrderResponse } from './pageOrderResponse';
import type { ApiError } from './apiError';

export interface ApiResponsePageOrderResponse {
  success?: boolean;
  data?: PageOrderResponse;
  message?: string;
  error?: ApiError;
}
