/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Zone } from './zone';
import type { ApiError } from './apiError';

export interface ApiResponseZone {
  success?: boolean;
  data?: Zone;
  message?: string;
  error?: ApiError;
}
