/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DnsRecordResponse } from './dnsRecordResponse';
import type { ApiError } from './apiError';

export interface ApiResponseDnsRecordResponse {
  success?: boolean;
  data?: DnsRecordResponse;
  message?: string;
  error?: ApiError;
}
