/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DomainSearchResult } from './domainSearchResult';
import type { ApiError } from './apiError';

export interface ApiResponseListDomainSearchResult {
  success?: boolean;
  data?: DomainSearchResult[];
  message?: string;
  error?: ApiError;
}
