/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { NsDelegationResponse } from './nsDelegationResponse';
import type { ApiError } from './apiError';

export interface ApiResponseNsDelegationResponse {
  success?: boolean;
  data?: NsDelegationResponse;
  message?: string;
  error?: ApiError;
}
