/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Notification Service API
 * OpenAPI spec version: 1.0.0
 */
import type { PageDomainExpiryMonitoringResponse } from './pageDomainExpiryMonitoringResponse';
import type { ApiError } from './apiError';

export interface ApiResponsePageDomainExpiryMonitoringResponse {
  success?: boolean;
  data?: PageDomainExpiryMonitoringResponse;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  error?: ApiError;
}
