/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CartResponse } from './cartResponse';
import type { ApiError } from './apiError';

export interface ApiResponseCartResponse {
  success?: boolean;
  data?: CartResponse;
  message?: string;
  error?: ApiError;
}
