/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageZone } from './pageZone';
import type { ApiError } from './apiError';

export interface ApiResponsePageZone {
  success?: boolean;
  data?: PageZone;
  message?: string;
  error?: ApiError;
}
