/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Notification Service API
 * OpenAPI spec version: 1.0.0
 */
import type { MonitoringDashboardResponse } from './monitoringDashboardResponse';
import type { ApiError } from './apiError';

export interface ApiResponseMonitoringDashboardResponse {
  success?: boolean;
  data?: MonitoringDashboardResponse;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  error?: ApiError;
}
