/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Notification Service API
 * OpenAPI spec version: 1.0.0
 */
import type { DomainExpiryAlertResponse } from './domainExpiryAlertResponse';
import type { ApiError } from './apiError';

export interface ApiResponseDomainExpiryAlertResponse {
  success?: boolean;
  data?: DomainExpiryAlertResponse;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  error?: ApiError;
}
