/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Notification Service API
 * OpenAPI spec version: 1.0.0
 */
import type { NotificationPreferencesResponse } from './notificationPreferencesResponse';
import type { ApiError } from './apiError';

export interface ApiResponseNotificationPreferencesResponse {
  success?: boolean;
  data?: NotificationPreferencesResponse;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  error?: ApiError;
}
