/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseVoidData } from './apiResponseVoidData';
import type { ApiError } from './apiError';

export interface ApiResponseVoid {
  success?: boolean;
  data?: ApiResponseVoidData;
  message?: string;
  error?: ApiError;
}
