/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageDomainResponse } from './pageDomainResponse';
import type { ApiError } from './apiError';

export interface ApiResponsePageDomainResponse {
  success?: boolean;
  data?: PageDomainResponse;
  message?: string;
  error?: ApiError;
}
