/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type CartItemResponseTerm =
  (typeof CartItemResponseTerm)[keyof typeof CartItemResponseTerm];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CartItemResponseTerm = {
  monthly: 'monthly',
  yearly: 'yearly',
} as const;
