/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CartItemResponse } from './cartItemResponse';

export interface CartResponse {
  id?: string;
  userId?: string;
  items?: CartItemResponse[];
  createdAt?: string;
  updatedAt?: string;
}
