/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CartItemResponseAction } from './cartItemResponseAction';
import type { CartItemResponseTerm } from './cartItemResponseTerm';

export interface CartItemResponse {
  id?: string;
  action?: CartItemResponseAction;
  term?: CartItemResponseTerm;
  fqdn?: string;
  price?: number;
  createdAt?: string;
  updatedAt?: string;
}
