/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CreateDomainRequest {
  fqdn: string;
  zoneId: string;
  expiresAt: string;
}
