/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CreateMxRecordRequest {
  domainId: string;
  name: string;
  mailExchange: string;
  /** @minimum 0 */
  priority: number;
  ttl: number;
}
