/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CreateCaaRecordRequest {
  domainId: string;
  name: string;
  /** @pattern ^[0-9]$ */
  flags: string;
  /** @pattern ^(issue|issuewild|iodef)$ */
  tag: string;
  value: string;
  ttl: number;
}
