/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CreateTxtRecordRequest {
  domainId: string;
  name: string;
  textValue: string;
  ttl: number;
}
