/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CreateSrvRecordRequest {
  domainId: string;
  serviceName: string;
  target: string;
  /** @minimum 0 */
  priority: number;
  /**
   * @minimum 0
   * @maximum 65535
   */
  weight: number;
  /**
   * @minimum 1
   * @maximum 65535
   */
  port: number;
  ttl: number;
}
