/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CreateCnameRecordRequest {
  domainId: string;
  name: string;
  canonicalName: string;
  ttl: number;
}
