/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Notification Service API
 * OpenAPI spec version: 1.0.0
 */

export interface DomainExpiryMonitoringResponse {
  domainId?: string;
  fqdn?: string;
  expiresAt?: string;
  /** @nullable */
  activatedAt?: string | null;
  daysUntilExpiry?: number;
  alertSent?: boolean;
  /** @nullable */
  lastAlertSentAt?: string | null;
}
