/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Notification Service API
 * OpenAPI spec version: 1.0.0
 */

export interface ExpiryAlertPreference {
  id?: string;
  daysBefore?: number;
  enabled?: boolean;
}
