/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Domain Order Service API
 * OpenAPI spec version: 1.0.0
 */

export type GetDomainsParams = {
  /**
   * @minimum 0
   */
  page?: number;
  /**
   * @minimum 1
   */
  size?: number;
  sort?: string[];
};
