/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Domain Order Service API
 * OpenAPI spec version: 1.0.0
 */

export type ItemTerm = (typeof ItemTerm)[keyof typeof ItemTerm];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ItemTerm = {
  monthly: 'monthly',
  yearly: 'yearly',
} as const;
