/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Notification Service API
 * OpenAPI spec version: 1.0.0
 */

export interface MonitoringDashboardResponse {
  domainsExpiringIn30Days?: number;
  domainsExpiringIn14Days?: number;
  domainsExpiringIn7Days?: number;
  domainsExpiringIn3Days?: number;
  domainsExpiringIn1Day?: number;
  expiredDomains?: number;
  totalActiveDomains?: number;
}
