/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Notification Service API
 * OpenAPI spec version: 1.0.0
 */
import type { ExpiryAlertPreference } from './expiryAlertPreference';

export interface NotificationPreferencesResponse {
  expiryAlerts?: ExpiryAlertPreference[];
  orderNotificationsEnabled?: boolean;
  paymentNotificationsEnabled?: boolean;
  domainActivationNotificationsEnabled?: boolean;
}
