/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type OrderItemResponseAction =
  (typeof OrderItemResponseAction)[keyof typeof OrderItemResponseAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderItemResponseAction = {
  register: 'register',
  renew: 'renew',
} as const;
