/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type OrderResponseStatus =
  (typeof OrderResponseStatus)[keyof typeof OrderResponseStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderResponseStatus = {
  created: 'created',
  pending_payment: 'pending_payment',
  paid: 'paid',
  cancelled: 'cancelled',
  failed: 'failed',
} as const;
