/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type OrderItemResponseTerm =
  (typeof OrderItemResponseTerm)[keyof typeof OrderItemResponseTerm];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderItemResponseTerm = {
  monthly: 'monthly',
  yearly: 'yearly',
} as const;
