/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrderItemResponseAction } from './orderItemResponseAction';
import type { OrderItemResponseTerm } from './orderItemResponseTerm';

export interface OrderItemResponse {
  id?: string;
  action?: OrderItemResponseAction;
  term?: OrderItemResponseTerm;
  domainId?: string;
  createdAt?: string;
  updatedAt?: string;
}
