/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrderResponseStatus } from './orderResponseStatus';
import type { OrderItemResponse } from './orderItemResponse';

export interface OrderResponse {
  id?: string;
  userId?: string;
  status?: OrderResponseStatus;
  totalAmount?: number;
  items?: OrderItemResponse[];
  createdAt?: string;
  paidAt?: string;
  updatedAt?: string;
}
