/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Notification Service API
 * OpenAPI spec version: 1.0.0
 */
import type { DomainExpiryMonitoringResponse } from './domainExpiryMonitoringResponse';

export interface PageDomainExpiryMonitoringResponse {
  content?: DomainExpiryMonitoringResponse[];
  totalElements?: number;
  totalPages?: number;
  size?: number;
  number?: number;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  empty?: boolean;
}
