/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrderResponse } from './orderResponse';
import type { SortObject } from './sortObject';
import type { PageableObject } from './pageableObject';

export interface PageOrderResponse {
  totalPages?: number;
  totalElements?: number;
  first?: boolean;
  size?: number;
  content?: OrderResponse[];
  number?: number;
  sort?: SortObject[];
  numberOfElements?: number;
  pageable?: PageableObject;
  last?: boolean;
  empty?: boolean;
}
