/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Notification Service API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type SendNotificationRequestParameters = {
  [key: string]: unknown;
} | null;
