/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Notification Service API
 * OpenAPI spec version: 1.0.0
 */
import type { NotificationType } from './notificationType';
import type { SendNotificationRequestParameters } from './sendNotificationRequestParameters';

export interface SendNotificationRequest {
  userId: string;
  type: NotificationType;
  /** @nullable */
  subject?: string | null;
  /** @nullable */
  template?: string | null;
  /** @nullable */
  parameters?: SendNotificationRequestParameters;
}
