/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UpdateDnsRecordRequest {
  value: string;
  ttl: number;
  priority?: number;
  weight?: number;
  port?: number;
  flags?: string;
  tag?: string;
}
