/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Notification Service API
 * OpenAPI spec version: 1.0.0
 */
import type { ExpiryAlertPreference } from './expiryAlertPreference';

export interface UpdateNotificationPreferencesRequest {
  expiryAlerts?: ExpiryAlertPreference[];
  /** @nullable */
  orderNotificationsEnabled?: boolean | null;
  /** @nullable */
  paymentNotificationsEnabled?: boolean | null;
  /** @nullable */
  domainActivationNotificationsEnabled?: boolean | null;
}
