/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface Zone {
  id?: string;
  name?: string;
  price?: number;
  createdAt?: string;
  updatedAt?: string;
}
